name: tableformer_fast_jpqd
description: TableFormer fast model for real-time table structure recognition, optimized with JPQD quantization
framework: ONNX
task: table-structure-recognition
domain: computer-vision
subdomain: document-analysis

model_info:
  architecture: TableFormer (Transformer-based, optimized)
  paper: "TableFormer: Table Structure Understanding With Transformers"
  paper_url: "https://doi.org/10.1109/CVPR52688.2022.00457"
  original_source: Docling
  original_repo: "https://github.com/DS4SD/docling"
  optimization: JPQD quantization
  variant: fast
  
specifications:
  input_shape: [1, 10]  # Based on model analysis
  input_type: int64
  input_format: Processed table features
  output_shape: [1, 10]
  output_type: float32
  batch_size: dynamic
  
performance:
  teds_score_simple: "~94.0"  # Slightly lower than accurate
  teds_score_complex: "~88.0"  # Slightly lower than accurate
  teds_score_overall: "~91.0"  # Slightly lower than accurate
  inference_time_cpu_ms: ~0.7  # Faster than accurate
  accuracy_retention: ">95%"
  speed_improvement: "~30% faster than accurate variant"
  
deployment:
  runtime: onnxruntime
  hardware: CPU-optimized
  precision: INT8 weights, FP32 activations
  memory_usage_mb: ~25
  
usage:
  preprocessing:
    - Extract table regions from document images
    - Apply TableFormer-specific preprocessing
    - Convert to model input format
  postprocessing:
    - Parse table structure predictions
    - Extract cell boundaries and types
    - Generate structured table representation

benchmarks:
  dataset: PubTabNet, FinTabNet
  metric: TEDS (Tree-Edit-Distance-based Similarity)
  trade_off: "Balanced accuracy vs speed"
  use_case: "Real-time applications, bulk processing"

applications:
  - Real-time document processing
  - Interactive table extraction
  - Bulk document conversion
  - Mobile applications
  - Edge deployment scenarios
  - High-throughput pipelines

recommended_for:
  - Interactive applications
  - Real-time processing requirements
  - Resource-constrained environments
  - Batch processing workflows
  - Mobile and edge deployment

license: cdla-permissive-2.0
tags:
  - table-structure-recognition
  - tableformer
  - document-analysis
  - onnx
  - quantized
  - jpqd
  - docling
  - fast
  - real-time